# Generated by Django 5.0.2 on 2024-05-23 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('can_create_course', 'Can create course'), ('can_change_course', 'Can change course'), ('can_delete_course', 'Can delete course')]},
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(choices=[('python', 'Основы Python'), ('web', 'Основы Web на Python'), ('django', 'Основы Django')], default='null', max_length=20),
            preserve_default=False,
        ),
    ]
