# Generated by Django 5.0.2 on 2024-05-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_remove_course_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
