# Generated by Django 5.0.2 on 2024-05-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.TextField(default='Text of assignment'),
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default='Text of the course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='Short description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='Short description'),
        ),
    ]
